table Cont_op
	lineageTag: 9a984f2c-3318-44f8-a31f-af66beb2e7f7

	measure 'Itens (Cont_op)' =
			COUNTROWS ( Cont_op )
		formatString: #,0
		lineageTag: 85be226a-baf3-4695-b449-cdfbd45c755a

	measure 'Itens com RT em avanço' =
			CALCULATE ( COUNTROWS ( Cont_op ), Cont_op[Motivo da RT em avanço] <> BLANK () )
		formatString: #,0
		lineageTag: 0cf8cbc3-86e0-4ee7-b750-255e03009a8f

	column ID
		dataType: int64
		formatString: 0
		lineageTag: b756b0ef-6843-42a8-9b11-dae2015f99fd
		summarizeBy: none
		sourceColumn: ID

	column 'Chave (Poço+Fase+PIOS)'
		dataType: string
		lineageTag: 75bcf227-1142-4a7f-8d5d-84fbabc3f36f
		summarizeBy: none
		sourceColumn: Chave (Poço+Fase+PIOS)

	column NP
		dataType: string
		lineageTag: a1627488-fb9c-4af0-92f2-685443f4fc08
		summarizeBy: none
		sourceColumn: NP

	column NS
		dataType: string
		lineageTag: 3c9de17b-864a-4c72-b742-1f07182187de
		summarizeBy: none
		sourceColumn: NS

	column NP_Norm
		dataType: string
		lineageTag: fa3036ba-9dbd-4e02-aeb7-1bcf3203fe94
		summarizeBy: none
		sourceColumn: NP_Norm

	column NS_Norm
		dataType: string
		lineageTag: e555f197-7202-4a0e-a716-e6210f681642
		summarizeBy: none
		sourceColumn: NS_Norm

	column NP_NS
		dataType: string
		lineageTag: 2cc3f751-676e-4de4-b7c4-a741e6dfe862
		summarizeBy: none
		sourceColumn: NP_NS

	column 'Descrição'
		dataType: string
		lineageTag: 6561b3c2-b863-486e-b510-69b954499172
		summarizeBy: none
		sourceColumn: Descrição

	column Fase
		dataType: string
		lineageTag: 886d8cf3-42aa-4148-a2c6-41dcb3d986b6
		summarizeBy: none
		sourceColumn: Fase

	column TAG
		dataType: string
		lineageTag: 39537616-4acc-4ad1-8e77-6fab23d93973
		summarizeBy: none
		sourceColumn: TAG

	column 'Sonda / Barco'
		dataType: string
		lineageTag: 390a1fdd-95f0-403e-8ffb-22d7c0f1cc74
		summarizeBy: none
		sourceColumn: Sonda / Barco

	column 'Poço'
		dataType: string
		lineageTag: 68c1e606-91a2-4342-93d9-6d5163b94490
		summarizeBy: none
		sourceColumn: Poço

	column 'Responsável DISP'
		dataType: string
		lineageTag: 35c85ebd-65a7-425c-906f-f8b8159434f0
		summarizeBy: none
		sourceColumn: Responsável DISP

	column 'Status Processo'
		dataType: string
		lineageTag: 70852619-99eb-444a-9fb1-69de294b7a54
		summarizeBy: none
		sourceColumn: Status Processo

	column 'Status manutenção'
		dataType: string
		lineageTag: eba2b10a-a373-4788-af5f-3fdd68795cd3
		summarizeBy: none
		sourceColumn: Status manutenção

	column 'Vencimento da manutenção'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e022f236-4e8c-4869-ad52-b9a4d994be11
		summarizeBy: none
		sourceColumn: Vencimento da manutenção

	column Venc_Final
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 00885e9d-50cb-4b2a-b706-33b4ea8d39c6
		summarizeBy: none
		sourceColumn: Venc_Final

	column Venc_Origem
		dataType: string
		lineageTag: 66a35563-05bd-4903-a10a-0ac61a268509
		summarizeBy: none
		sourceColumn: Venc_Origem

	column 'Status PCM'
		dataType: string
		lineageTag: f3805c47-b662-4f7e-91c3-87fcdb300026
		summarizeBy: none
		sourceColumn: Status PCM

	column 'Motivo da RT em avanço'
		dataType: string
		lineageTag: 3b701ab3-41ea-4844-b1ea-4a141c777248
		summarizeBy: none
		sourceColumn: Motivo da RT em avanço

	column 'Relatório de END'
		dataType: string
		lineageTag: d6e8ba27-f2f5-4de9-8154-e1cdf4248bb8
		summarizeBy: none
		sourceColumn: Relatório de END

	partition Cont_op = m
		mode: import
		source =
			let
			    Fonte = SharePoint.Tables(SiteContOp, [ApiVersion = 15]),
			    Lista = Fonte{[Title = NomeListaContOp]}[Items],
			    Colunas = {"ID", "Poço + Fase + PIOS", "NP", "NS", "DESCRIÇÃO", "Fase", "TAG", "Sonda / Barco", "Poço", "Responsável DISP", "Status Processo", "Status manutenção", "Vencimento da manutenção", "Status PCM", "Motivo da RT em avanço", "Relatório de END"},
			    // MissingField.UseNull: se um nome de coluna diferir no SharePoint, a coluna fica vazia em vez de quebrar a atualização
			    Sel = Table.SelectColumns(Lista, Colunas, MissingField.UseNull),
			    ComId = Table.SelectRows(Sel, each [ID] <> null),
			    Renom = Table.RenameColumns(ComId, {{"Poço + Fase + PIOS", "Chave (Poço+Fase+PIOS)"}, {"DESCRIÇÃO", "Descrição"}}),
			    Tipos = Table.TransformColumnTypes(Renom, {{"ID", Int64.Type}, {"NP", type text}, {"NS", type text}, {"Descrição", type text}, {"Fase", type text}, {"TAG", type text}, {"Sonda / Barco", type text}, {"Poço", type text}, {"Responsável DISP", type text}, {"Status Processo", type text}, {"Status manutenção", type text}, {"Status PCM", type text}, {"Motivo da RT em avanço", type text}, {"Relatório de END", type text}}),
			    // data que nunca gera erro: o que não for data vira null
			    Venc = Table.TransformColumns(Tipos, {{"Vencimento da manutenção", each try Date.From(_) otherwise null, type nullable date}}),
			    NPn = Table.AddColumn(Venc, "NP_Norm", each fNormalizaNP([NP]), type text),
			    NSn = Table.AddColumn(NPn, "NS_Norm", each fNormalizaNS([NS]), type text),
			    Chave = Table.AddColumn(NSn, "NP_NS", each if [NP_Norm] = null then null else [NP_Norm] & "|" & (if [NS_Norm] = null then "" else Text.Upper([NS_Norm])), type text),
			    St = Table.AddColumn(Chave, "St", each fParseStatusManutencao([Status manutenção])),
			    VencF = Table.AddColumn(St, "Venc_Final", each if [Vencimento da manutenção] <> null then [Vencimento da manutenção] else [St][Venc], type nullable date),
			    Orig = Table.AddColumn(VencF, "Venc_Origem", each if [Vencimento da manutenção] <> null then "Coluna" else if [St][Venc] <> null then "Texto do status" else null, type text),
			    SemSt = Table.RemoveColumns(Orig, {"St"}),
			    Vazios = Table.ReplaceValue(SemSt, "", null, Replacer.ReplaceValue, {"Motivo da RT em avanço", "Status Processo", "Status PCM"}),
			    Rotulo = Table.ReplaceValue(Vazios, null, "(sem status)", Replacer.ReplaceValue, {"Status Processo", "Status PCM"}),
			    Ordem = Table.ReorderColumns(Rotulo, {"ID", "Chave (Poço+Fase+PIOS)", "NP", "NS", "NP_Norm", "NS_Norm", "NP_NS", "Descrição", "Fase", "TAG", "Sonda / Barco", "Poço", "Responsável DISP", "Status Processo", "Status manutenção", "Vencimento da manutenção", "Venc_Final", "Venc_Origem", "Status PCM", "Motivo da RT em avanço", "Relatório de END"})
			in
			    Ordem
