table Cont_op
	lineageTag: a284e6b9-0189-4a66-acf2-951b1b572edf

	measure 'Itens (Cont_op)' =
			COUNTROWS ( Cont_op )
		formatString: #,0
		lineageTag: 42598f1e-75c6-4d92-99e7-f55b00bf4586

	measure 'Itens com RT em avanço' =
			CALCULATE ( COUNTROWS ( Cont_op ), Cont_op[Motivo da RT em avanço] <> BLANK () )
		formatString: #,0
		lineageTag: 1726ad2f-58b2-4593-92d0-c3d7a8ffb3c0

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 5880a2af-f965-4f88-890f-bc93a0583269
		summarizeBy: none
		sourceColumn: ID

	column 'Chave (Poço+Fase+PIOS)'
		dataType: string
		lineageTag: cd284c3e-02e9-45dd-8ff8-62f66618df5b
		summarizeBy: none
		sourceColumn: Chave (Poço+Fase+PIOS)

	column NP
		dataType: string
		lineageTag: ecf7d6e3-e976-48ee-9995-a67af83f6afc
		summarizeBy: none
		sourceColumn: NP

	column NS
		dataType: string
		lineageTag: 923a8361-938c-40cf-b5f1-7579ca6242d9
		summarizeBy: none
		sourceColumn: NS

	column NP_Norm
		dataType: string
		lineageTag: 025f103a-00c2-471e-874a-83b96deb7b26
		summarizeBy: none
		sourceColumn: NP_Norm

	column NS_Norm
		dataType: string
		lineageTag: bb4718c6-dee4-416e-bf9b-6b9fd6f6bd19
		summarizeBy: none
		sourceColumn: NS_Norm

	column NP_NS
		dataType: string
		lineageTag: 4c67df4b-9f1a-4e49-938d-204c317e67f3
		summarizeBy: none
		sourceColumn: NP_NS

	column 'Descrição'
		dataType: string
		lineageTag: 2283a449-b0e2-44db-ad11-0452b53b058c
		summarizeBy: none
		sourceColumn: Descrição

	column Fase
		dataType: string
		lineageTag: b1986580-f4c4-4479-b728-65239ba1f983
		summarizeBy: none
		sourceColumn: Fase

	column TAG
		dataType: string
		lineageTag: 3df699f4-5d01-42f3-98ae-dbfb42a9069a
		summarizeBy: none
		sourceColumn: TAG

	column 'Sonda / Barco'
		dataType: string
		lineageTag: a336a381-66cd-4d24-9b65-f15208ab2189
		summarizeBy: none
		sourceColumn: Sonda / Barco

	column 'Poço'
		dataType: string
		lineageTag: dfe81dc6-c0c8-41ac-b309-192de5066760
		summarizeBy: none
		sourceColumn: Poço

	column 'Responsável DISP'
		dataType: string
		lineageTag: e70ca4f6-2771-42cf-9f03-b9b9d0707ab0
		summarizeBy: none
		sourceColumn: Responsável DISP

	column 'Status Processo'
		dataType: string
		lineageTag: 872698a0-e136-4da5-9eb8-fdb6b5938ed8
		summarizeBy: none
		sourceColumn: Status Processo

	column 'Status manutenção'
		dataType: string
		lineageTag: 88518e8e-ad77-4f2e-9843-661ee5c51e49
		summarizeBy: none
		sourceColumn: Status manutenção

	column 'Vencimento da manutenção'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 19c09f0c-a554-493e-af8f-48205e4f3574
		summarizeBy: none
		sourceColumn: Vencimento da manutenção

	column Venc_Final
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d3f8960c-b232-4757-875e-1f497a6b5021
		summarizeBy: none
		sourceColumn: Venc_Final

	column Venc_Origem
		dataType: string
		lineageTag: 9e608d83-7bec-4610-bb41-440a3ffef1a0
		summarizeBy: none
		sourceColumn: Venc_Origem

	column 'Status PCM'
		dataType: string
		lineageTag: 35b29ec8-45df-4064-8f7c-c2c36b9d5035
		summarizeBy: none
		sourceColumn: Status PCM

	column 'Motivo da RT em avanço'
		dataType: string
		lineageTag: 1fd35c6e-b63d-4ae8-87a4-1620f1d3c3c9
		summarizeBy: none
		sourceColumn: Motivo da RT em avanço

	column 'Relatório de END'
		dataType: string
		lineageTag: f3800669-f810-468f-9913-d3bf54061afc
		summarizeBy: none
		sourceColumn: Relatório de END

	partition Cont_op = m
		mode: import
		source =
			let
			    Fonte = SharePoint.Tables(SiteContOp, [ApiVersion = 15]),
			    Lista = Fonte{[Title = NomeListaContOp]}[Items],
			    Colunas = {"ID", "Poço + Fase + PIOS", "NP", "NS", "DESCRIÇÃO", "Fase", "TAG", "Sonda / Barco", "Poço", "Responsável DISP", "Status Processo", "Status manutenção", "Vencimento da manutenção", "Status PCM", "Motivo da RT em avanço", "Relatório de END"},
			    // MissingField.UseNull: se um nome de coluna diferir no SharePoint, a coluna fica vazia em vez de quebrar a atualização
			    Sel = Table.SelectColumns(Lista, Colunas, MissingField.UseNull),
			    ComId = Table.SelectRows(Sel, each [ID] <> null),
			    Renom = Table.RenameColumns(ComId, {{"Poço + Fase + PIOS", "Chave (Poço+Fase+PIOS)"}, {"DESCRIÇÃO", "Descrição"}}),
			    Tipos = Table.TransformColumnTypes(Renom, {{"ID", Int64.Type}, {"NP", type text}, {"NS", type text}, {"Descrição", type text}, {"Fase", type text}, {"TAG", type text}, {"Sonda / Barco", type text}, {"Poço", type text}, {"Responsável DISP", type text}, {"Status Processo", type text}, {"Status manutenção", type text}, {"Status PCM", type text}, {"Motivo da RT em avanço", type text}, {"Relatório de END", type text}}),
			    // data que nunca gera erro: o que não for data vira null
			    Venc = Table.TransformColumns(Tipos, {{"Vencimento da manutenção", each try Date.From(_) otherwise null, type nullable date}}),
			    NPn = Table.AddColumn(Venc, "NP_Norm", each fNormalizaNP([NP]), type text),
			    NSn = Table.AddColumn(NPn, "NS_Norm", each fNormalizaNS([NS]), type text),
			    Chave = Table.AddColumn(NSn, "NP_NS", each if [NP_Norm] = null then null else [NP_Norm] & "|" & (if [NS_Norm] = null then "" else Text.Upper([NS_Norm])), type text),
			    St = Table.AddColumn(Chave, "St", each fParseStatusManutencao([Status manutenção])),
			    VencF = Table.AddColumn(St, "Venc_Final", each if [Vencimento da manutenção] <> null then [Vencimento da manutenção] else [St][Venc], type nullable date),
			    Orig = Table.AddColumn(VencF, "Venc_Origem", each if [Vencimento da manutenção] <> null then "Coluna" else if [St][Venc] <> null then "Texto do status" else null, type text),
			    SemSt = Table.RemoveColumns(Orig, {"St"}),
			    Vazios = Table.ReplaceValue(SemSt, "", null, Replacer.ReplaceValue, {"Motivo da RT em avanço", "Status Processo", "Status PCM"}),
			    Rotulo = Table.ReplaceValue(Vazios, null, "(sem status)", Replacer.ReplaceValue, {"Status Processo", "Status PCM"}),
			    Ordem = Table.ReorderColumns(Rotulo, {"ID", "Chave (Poço+Fase+PIOS)", "NP", "NS", "NP_Norm", "NS_Norm", "NP_NS", "Descrição", "Fase", "TAG", "Sonda / Barco", "Poço", "Responsável DISP", "Status Processo", "Status manutenção", "Vencimento da manutenção", "Venc_Final", "Venc_Origem", "Status PCM", "Motivo da RT em avanço", "Relatório de END"})
			in
			    Ordem
