table END_ultimo
	lineageTag: cdb0821c-eb5b-48a5-bc06-5f67cc473253

	column NP_NS
		dataType: string
		lineageTag: dcfb066f-4f39-4a91-903b-dc349958e4ac
		summarizeBy: none
		sourceColumn: NP_NS

	column Validade_END
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e00e7621-7965-45f5-b5c0-2a4fb3e0140a
		summarizeBy: none
		sourceColumn: Validade_END

	column Registros_END
		dataType: int64
		formatString: 0
		lineageTag: eff1b033-685e-4497-8478-e0d6ee9feb7b
		summarizeBy: none
		sourceColumn: Registros_END

	column Datas_invalidas
		dataType: int64
		formatString: 0
		lineageTag: d198ac29-ff37-4dcb-8ab8-a9606ee4cd37
		summarizeBy: none
		sourceColumn: Datas_invalidas

	partition END_ultimo = m
		mode: import
		source =
			let
			    Fonte = SharePoint.Tables(SiteEND, [ApiVersion = 15]),
			    Lista = Fonte{[Title = NomeListaEND]}[Items],
			    Sel = Table.SelectColumns(Lista, {"NP", "NS", "Data de Validade"}, MissingField.UseNull),
			    Tx = Table.TransformColumnTypes(Sel, {{"NP", type text}, {"NS", type text}}),
			    // hoje a coluna é texto dd/mm/aaaa; se a lista passar a ter tipo Data, o ramo Date.From assume
			    Val = Table.AddColumn(Tx, "Validade", each let v = [Data de Validade] in if v = null then null else if Value.Is(v, type date) or Value.Is(v, type datetime) then Date.From(v) else fParseData(Text.From(v)), type nullable date),
			    NPn = Table.AddColumn(Val, "NP_Norm", each fNormalizaNP([NP]), type text),
			    Com = Table.SelectRows(NPn, each [NP_Norm] <> null),
			    Chave = Table.AddColumn(Com, "NP_NS", each let n = fNormalizaNS([NS]) in [NP_Norm] & "|" & (if n = null then "" else Text.Upper(n)), type text),
			    // regra confirmada: vale a MAIOR validade por NP+NS
			    Grp = Table.Group(Chave, {"NP_NS"}, {{"Validade_END", each List.Max([Validade]), type nullable date}, {"Registros_END", each Table.RowCount(_), Int64.Type}, {"Datas_invalidas", each List.Count(List.Select([Validade], each _ = null)), Int64.Type}})
			in
			    Grp
