table END_ultimo
	lineageTag: 4a715e21-a767-4992-b7dc-c6abd3094c07

	column NP_NS
		dataType: string
		lineageTag: b3264c29-f09d-4de6-84d0-2fe4ece4861f
		summarizeBy: none
		sourceColumn: NP_NS

	column Validade_END
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6716a055-6ede-43ac-bada-f02eccc426bc
		summarizeBy: none
		sourceColumn: Validade_END

	column Registros_END
		dataType: int64
		formatString: 0
		lineageTag: 2e18bc2d-09b7-444f-b8db-5fdc446ebc1f
		summarizeBy: none
		sourceColumn: Registros_END

	column Datas_invalidas
		dataType: int64
		formatString: 0
		lineageTag: ce05d221-ee0c-4f33-ab2c-941a0eb1a404
		summarizeBy: none
		sourceColumn: Datas_invalidas

	partition END_ultimo = m
		mode: import
		source =
			let
			    Fonte = SharePoint.Tables(SiteEND, [ApiVersion = 15]),
			    Lista = Fonte{[Title = NomeListaEND]}[Items],
			    Sel = Table.SelectColumns(Lista, {"NP", "NS", "Data de Validade"}, MissingField.UseNull),
			    Tx = Table.TransformColumnTypes(Sel, {{"NP", type text}, {"NS", type text}}),
			    // hoje a coluna é texto dd/mm/aaaa; se a lista passar a ter tipo Data, o ramo Date.From assume
			    Val = Table.AddColumn(Tx, "Validade", each let v = [Data de Validade] in if v = null then null else if Value.Is(v, type date) or Value.Is(v, type datetime) then Date.From(v) else fParseData(Text.From(v)), type nullable date),
			    NPn = Table.AddColumn(Val, "NP_Norm", each fNormalizaNP([NP]), type text),
			    Com = Table.SelectRows(NPn, each [NP_Norm] <> null),
			    Chave = Table.AddColumn(Com, "NP_NS", each let n = fNormalizaNS([NS]) in [NP_Norm] & "|" & (if n = null then "" else Text.Upper(n)), type text),
			    // regra confirmada: vale a MAIOR validade por NP+NS
			    Grp = Table.Group(Chave, {"NP_NS"}, {{"Validade_END", each List.Max([Validade]), type nullable date}, {"Registros_END", each Table.RowCount(_), Int64.Type}, {"Datas_invalidas", each List.Count(List.Select([Validade], each _ = null)), Int64.Type}})
			in
			    Grp
