table Vencimentos
	lineageTag: c6189d63-6c19-45e9-900c-b7b86cecd313

	measure 'Itens na Faixa' =
			VAR o = SELECTEDVALUE ( Faixa_Venc[Ordem] )
			VAR mn = SELECTEDVALUE ( Faixa_Venc[Dias Min] )
			VAR mx = SELECTEDVALUE ( Faixa_Venc[Dias Max] )
			VAR hoje = TODAY ()
			RETURN
			    IF (
			        ISBLANK ( o ),
			        COUNTROWS ( Vencimentos ),
			        COUNTROWS (
			            FILTER (
			                Vencimentos,
			                VAR d = Vencimentos[Data]
			                VAR dias = DATEDIFF ( hoje, d, DAY )
			                RETURN
			                    IF ( o = 6, ISBLANK ( d ), NOT ISBLANK ( d ) && dias >= mn && dias <= mx )
			            )
			        ) + 0
			    )
		formatString: #,0
		lineageTag: ff7e9e32-d3bf-4db2-bcdc-60242936d2ca

	measure 'Dias até vencer' =
			MINX (
			    Vencimentos,
			    IF ( ISBLANK ( Vencimentos[Data] ), BLANK (), DATEDIFF ( TODAY (), Vencimentos[Data], DAY ) )
			)
		formatString: 0
		lineageTag: 20740970-e8a8-4443-bcee-43da7e589d9e

	column Cont_op_ID
		dataType: int64
		formatString: 0
		lineageTag: 555721a3-3128-4b7d-897f-6d17988e11b4
		summarizeBy: none
		sourceColumn: Cont_op_ID

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ad650467-2ae1-4a3c-b0f6-b2ba6c355620
		summarizeBy: none
		sourceColumn: Data

	column Tipo
		dataType: string
		lineageTag: 640e2900-0b9c-4f7d-b6a7-8797afbb637a
		summarizeBy: none
		sourceColumn: Tipo

	partition Vencimentos = m
		mode: import
		source =
			let
			    Base = Table.SelectColumns(Cont_op, {"ID", "NP_NS", "Venc_Final"}),
			    Manut = Table.AddColumn(Table.RenameColumns(Table.SelectColumns(Base, {"ID", "Venc_Final"}), {{"ID", "Cont_op_ID"}, {"Venc_Final", "Data"}}), "Tipo", each "Manutenção FRT/EQP", type text),
			    // END: só itens cujo NP+NS existe na lista de END (inner join); a data é a maior validade
			    J = Table.NestedJoin(Table.SelectColumns(Base, {"ID", "NP_NS"}), {"NP_NS"}, END_ultimo, {"NP_NS"}, "E", JoinKind.Inner),
			    Ex = Table.ExpandTableColumn(J, "E", {"Validade_END"}, {"Data"}),
			    EndT = Table.AddColumn(Table.RenameColumns(Table.SelectColumns(Ex, {"ID", "Data"}), {{"ID", "Cont_op_ID"}}), "Tipo", each "END", type text),
			    Uni = Table.Combine({Manut, EndT}),
			    Tip = Table.TransformColumnTypes(Uni, {{"Cont_op_ID", Int64.Type}, {"Data", type date}, {"Tipo", type text}})
			in
			    Tip
