table Vencimentos
	lineageTag: 73fb4f2d-4f71-4b1f-942e-11f437d1cc12

	measure 'Itens na Faixa' =
			VAR o = SELECTEDVALUE ( Faixa_Venc[Ordem] )
			VAR mn = SELECTEDVALUE ( Faixa_Venc[Dias Min] )
			VAR mx = SELECTEDVALUE ( Faixa_Venc[Dias Max] )
			VAR hoje = TODAY ()
			RETURN
			    IF (
			        ISBLANK ( o ),
			        COUNTROWS ( Vencimentos ),
			        COUNTROWS (
			            FILTER (
			                Vencimentos,
			                VAR d = Vencimentos[Data]
			                VAR dias = DATEDIFF ( hoje, d, DAY )
			                RETURN
			                    IF ( o = 6, ISBLANK ( d ), NOT ISBLANK ( d ) && dias >= mn && dias <= mx )
			            )
			        ) + 0
			    )
		formatString: #,0
		lineageTag: c884e3c0-78fc-4b30-9db3-ffe5f02de980

	measure 'Dias até vencer' =
			MINX (
			    Vencimentos,
			    IF ( ISBLANK ( Vencimentos[Data] ), BLANK (), DATEDIFF ( TODAY (), Vencimentos[Data], DAY ) )
			)
		formatString: 0
		lineageTag: ec447d54-9dbb-4bee-8d2f-6bfaa96f8287

	column Cont_op_ID
		dataType: int64
		formatString: 0
		lineageTag: 3f640cb7-b8fa-47e3-ae9a-c03cbf2675ab
		summarizeBy: none
		sourceColumn: Cont_op_ID

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d02417fb-a379-4ca1-b3f7-142b8ee5d615
		summarizeBy: none
		sourceColumn: Data

	column Tipo
		dataType: string
		lineageTag: 03e3a60e-61ae-4ef6-b93c-f71148306057
		summarizeBy: none
		sourceColumn: Tipo

	partition Vencimentos = m
		mode: import
		source =
			let
			    Base = Table.SelectColumns(Cont_op, {"ID", "NP_NS", "Venc_Final"}),
			    Manut = Table.AddColumn(Table.RenameColumns(Table.SelectColumns(Base, {"ID", "Venc_Final"}), {{"ID", "Cont_op_ID"}, {"Venc_Final", "Data"}}), "Tipo", each "Manutenção FRT/EQP", type text),
			    // END: só itens cujo NP+NS existe na lista de END (inner join); a data é a maior validade
			    J = Table.NestedJoin(Table.SelectColumns(Base, {"ID", "NP_NS"}), {"NP_NS"}, END_ultimo, {"NP_NS"}, "E", JoinKind.Inner),
			    Ex = Table.ExpandTableColumn(J, "E", {"Validade_END"}, {"Data"}),
			    EndT = Table.AddColumn(Table.RenameColumns(Table.SelectColumns(Ex, {"ID", "Data"}), {{"ID", "Cont_op_ID"}}), "Tipo", each "END", type text),
			    Uni = Table.Combine({Manut, EndT}),
			    Tip = Table.TransformColumnTypes(Uni, {{"Cont_op_ID", Int64.Type}, {"Data", type date}, {"Tipo", type text}})
			in
			    Tip
